routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
	
	return view('auth.login');
});


	Route::prefix('admin')->group(function () {

		
		

		Route::get('/home', 'AdminController@index')->name('dashboard');


		Route::get('/relatorio','AdminController@relatorioCompleto');


		Route::resource('/empresas','EmpresasController');
		Route::resource('/unidades','UnidadesController');
		Route::resource('/servicos','ServicosController');
		Route::resource('/taxas','TaxasController');
		Route::resource('/pendencia','PendenciasController');
		Route::resource('/arquivo','ArquivosController');
		

		
		Route::get('/faturamentos', 'FaturamentoController@index')->name('faturamentos.index');
		Route::get('/faturamento/show/{id}', 'FaturamentoController@show')->name('faturamento.show');

		Route::get('/faturamento/delete/{id}', 'FaturamentoController@destroy')->name('faturamento.destroy');

		Route::post('/faturamento/addNF','FaturamentoController@addNF')->name('faturamento.addNF');


		Route::get('/faturamento/create','FaturamentoController@create')->name('faturamento.create');
		Route::post('/faturamento/step2','FaturamentoController@step2')->name('faturamento.step2');
		Route::post('/faturamento/step3','FaturamentoController@step3')->name('faturamento.step3');
		Route::post('/faturamento/step4','FaturamentoController@step4')->name('faturamento.step4');


		
		Route::get('/reembolsos', 'ReembolsoController@index')->name('reembolsos.index');
		Route::get('/reembolso/show/{id}', 'ReembolsoController@show')->name('reembolso.show');
		Route::get('/reembolso/delete/{id}', 'ReembolsoController@destroy')->name('reembolso.destroy');

		Route::get('/reembolso/create','ReembolsoController@create')->name('reembolso.create');
		Route::post('/reembolso/step2','ReembolsoController@step2')->name('reembolso.step2');
		Route::post('/reembolso/step3','ReembolsoController@step3')->name('reembolso.step3');
		Route::post('/reembolso/step4','ReembolsoController@step4')->name('reembolso.step4');


		Route::get('/empresa/{empresa}/unidades','EmpresasController@unidades')->name('empresa.unidades');
		Route::get('/empresa/cadastro', 'EmpresasController@cadastro')->name('empresa.cadastro');
		Route::get('/unidade/cadastro', 'UnidadesController@cadastro')->name('unidade.cadastro');
		Route::post('/unidade/{id}', 'UnidadesController@editar')->name('unidade.editar');
		Route::get('/unidade/{id}', 'UnidadesController@delete')->name('unidade.delete');
		Route::post('/empresa/{id}', 'EmpresasController@editar')->name('empresa.editar');

		Route::get('/empresa/{id}', 'EmpresasController@delete')->name('empresa.delete');

		Route::get('/usuarios', 'UsersController@index')->name('usuarios.index');
		Route::get('/usuario/cadastro', 'UsersController@cadastro')->name('usuario.cadastro');
		Route::get('/usuario/editar/{id}', 'UsersController@editar')->name('usuario.editar');
		Route::post('/usuario/editar/{id}', 'UsersController@update')->name('usuario.update');
		Route::post('/usuario','UsersController@store')->name('usuario.store');
		Route::get('/usuario/delete/{id}', 'UsersController@delete')->name('usuario.delete');

		Route::get('/servico/delete/{id}','ServicosController@delete')->name('servico.delete');

		Route::get('/pendencia/done/{id}', 'PendenciasController@done')->name('pendencia.done');
		Route::get('/pendencia/undone/{id}', 'PendenciasController@undone')->name('pendencia.undone');
		Route::get('/pendencia/create/{servico_id}', 'PendenciasController@create')->name('pendencia.create');
		Route::get('/pendencia/delete/{id}', 'PendenciasController@delete')->name('pendencia.delete');
		
		Route::get('/pendencias/minhas', 'PendenciasController@minhas')->name('pendencias.minhas');
		Route::get('/pendencias/outras', 'PendenciasController@outras')->name('pendencias.outras');


		Route::get('/taxa/delete/{id}', 'TaxasController@delete')->name('taxas.delete');


		Route::get('/servico/andamento/', 'ServicosController@listaAndamento')->name('servico.andamento');
		Route::get('/servico/finalizados/', 'ServicosController@listaFinalizados')->name('servico.finalizado');
		Route::get('/servico/vigentes/', 'ServicosController@listaVigentes')->name('servico.vigente');
		Route::get('/servico/vencidos/', 'ServicosController@listaVencidos')->name('servico.vencido');
		Route::get('/servico/vencer/', 'ServicosController@listaVencer')->name('servico.vencer');
		Route::get('/servico/inativos/', 'ServicosController@listaInativo')->name('servico.inativo');
		Route::get('/servico/lista/', 'ServicosController@lista')->name('servico.lista');
		Route::get('/servico/arquivados/', 'ServicosController@listaArquivados')->name('servico.arquivado');

		Route::get('/servico/renovar/{id}', 'ServicosController@renovar')->name('servico.renovar');


		Route::get('/arquivo/download/{id}', 'ArquivosController@download')->name('arquivo.download');
		Route::get('/arquivo/delete/{id}', 'ArquivosController@delete')->name('arquivo.delete');


		Route::post('salvarInteracao', 'ServicosController@salvarInteracao')->name('interacao.store');


		
		Route::get('/servico/{id}/interacoes', 'ServicosController@interacoes')->name('interacoes.lista');


		
		

	});

	Route::prefix('cliente')->group(function () {

Route::get('/home', 'ClienteController@index')->name('cliente.home');
Route::get('/empresas', 'ClienteController@empresas')->name('cliente.empresas');
Route::get('/empresa/{id}', 'ClienteController@empresaShow')->name('cliente.empresa.show');
Route::get('/empresa/{id}/unidades', 'ClienteController@empresaUnidades')->name('cliente.empresa.unidades');
Route::get('/unidades', 'ClienteController@unidades')->name('cliente.unidades');
Route::get('/unidade/{id}', 'ClienteController@unidadeShow')->name('cliente.unidade.show');
Route::get('/servicos', 'ClienteController@servicos')->name('cliente.servicos');
Route::get('/servico/andamento/', 'ClienteController@listaAndamento')->name('cliente.servico.andamento');
Route::get('/servico/finalizados/', 'ClienteController@listaFinalizados')->name('cliente.servico.finalizado');
Route::get('/servico/vigentes/', 'ClienteController@listaVigentes')->name('cliente.servico.vigente');
Route::get('/servico/vencidos/', 'ClienteController@listaVencidos')->name('cliente.servico.vencido');
Route::get('/servico/vencer/', 'ClienteController@listaVencer')->name('cliente.servico.vencer');
Route::get('/servico/inativos/', 'ClienteController@listaInativo')->name('cliente.servico.inativo');
Route::get('/servico/{id}', 'ClienteController@servicoShow')->name('cliente.servico.show');
Route::post('salvarInteracao', 'ClienteController@salvarInteracao')->name('cliente.interacao.salvar');
Route::get('/servico/{id}/interacoes', 'ClienteController@interacoes')->name('cliente.interacoes.lista');
Route::get('/usuario/editar/', 'ClienteController@editarUsuario')->name('cliente.usuario.editar');
Route::post('/usuario/editar/', 'ClienteController@updateUsuario')->name('cliente.usuario.update');
Route::get('/servico/{id}/taxas/{taxa}','ClienteController@showTaxa')->name('cliente.taxa.show');

Route::post('/arquivo/anexar','ArquivosController@anexar')->name('cliente.arquivo.anexar');

			

	});

Route::get('/teste', function() {

		// $licenca = Servico::where('tipo','primario')->where('situacao','finalizado')->whereDate('licenca_validade','=',Carbon::now()->addDays(60))->get();

			$l = App\Models\Servico::find(589);

            $user = App\User::find($l->responsavel_id);
            $user->notify(new App\Notifications\Licenca60days($l,$user)); 

            return new App\Mail\VencimentoLicenca60days($l);

       


});


Route::get('/taxa/notify', 'TaxasController@notifyUser');


Route::get('/markAsRead', function()
{
	
	$notif_id = $_GET['notif_id'];
	auth()->user()->unreadNotifications->where('id', $notif_id)->markAsRead();
	return \Response::json($notif_id, 200);

});

Route::get('clearNotifications', function(){

	auth()->user()->notifications()->delete();
	return redirect()->back();
})->name('clearNotifications');

resources/views/admin/cadastro-pendencia.blade.php
@extends('adminlte::page')



@section('content')

	<div class="box box-primary">
	
	<div class="box-header with-border">
		<h3 class="box-title">Cadastrar pendência</h3>
	</div>

	

	{!! Form::open(['route'=>'pendencia.store']) !!}

	@include('admin.partials.form-pendencia')
	
	

      			<div class="box-footer">
      			            
                <button type="submit" class="btn btn-info">Cadastrar</button>
              	</div>
    	
    
	
	{!! Form::close() !!}

@endsection

resources/views/admin/cadastro-servico.blade.php
@extends('adminlte::page')



@section('content')



	<div class="box box-primary">
	
	<div class="box-header with-border">
		<h3 class="box-title">Cadastrar serviço</h3>
	</div>

	

	{!! Form::open(['route'=>'servicos.store','id'=>'cadastroServico','enctype'=>'multipart/form-data']) !!}


	@include('admin.partials.form-servico')

				<div class="box-footer">
                <a href="{{route('servicos.index')}}" class="btn btn-default">Voltar</a>
                <button type="submit" class="btn btn-info">Cadastrar</button>
              	</div>
    
	{!! Form::close() !!}

@endsection


@section('js')

<script>
	
	$(document).ready(function() {

  	$("#protocolo_emissao").datepicker();
  	$("#licenca_emissao").datepicker();
  	$("#licenca_validade").datepicker();
  	$("#laudo_emissao").datepicker();

  	$("#os").val("{!! $os !!}");  	
	


			var len = document.getElementById("servico_lpu").length;

			if(len)
					{
						// get reference to select element
					var sel = document.getElementById('servico_lpu');

					// create new option element
					var opt = document.createElement('option');

					// create text node to add to option element (opt)
					opt.appendChild( document.createTextNode('Selecione o tipo de serviço') );

					// set value property of opt
					opt.value = '0';

					opt.selected = true; 

					// add opt to end of select box (sel)
					sel.appendChild(opt);
					}
			else
					{
					var sel = document.getElementById('servico_lpu');

					// create new option element
					var opt = document.createElement('option');

					// create text node to add to option element (opt)
					opt.appendChild( document.createTextNode('Essa empresa não possui LPU') );
					sel.disabled = true;
					opt.selected = true;
					opt.value = '0';
					sel.appendChild(opt);

					}

		document.getElementById('tipoLicenca').onchange = function()
		{

			

			switch(document.getElementById('tipoLicenca').value)
			{
				case 'definitiva':
					document.getElementById('licenca_validade').disabled = true;
					document.getElementById('licenca_emissao').disabled = false;
					document.getElementById('licenca_validade').value = '31/12/2050';

				break;

				case 'n/a':

					document.getElementById('licenca_emissao').disabled = true;
					document.getElementById('licenca_validade').disabled = true;

					document.getElementById('licenca_validade').value = '';
					document.getElementById('licenca_emissao').value = '';
					

				break;

				case 'renovavel':
					document.getElementById('licenca_validade').value = '';
					document.getElementById('licenca_emissao').value = '';
					document.getElementById('licenca_emissao').disabled = false;
					document.getElementById('licenca_validade').disabled = false;
				break;
			}
		};
		

document.getElementById('servico_lpu').onchange = function() {
var selem = document.getElementById('servico_lpu'); 
document.getElementById('nome').value = selem.options[selem.selectedIndex].text;
}



 
});


</script>

@stop

resources/views/admin/cadastro-taxa.blade.php
@extends('adminlte::page')



@section('content')

	<div class="box box-primary">
	
	<div class="box-header with-border">
		<h3 class="box-title">Cadastrar taxa</h3>
	</div>

	

	{!! Form::open(['route'=>'taxas.store','enctype'=>'multipart/form-data']) !!}

	@include('admin.partials.form-taxa')
	
	

      			<div class="box-footer">
      			
                
                <button type="submit" class="btn btn-info">Cadastrar</button>
              	</div>
    	
    
	
	{!! Form::close() !!}

@endsection

@section('js')

<script>
	
	$(document).ready(function() {

  	$("#emissao").datepicker();
  	$("#vencimento").datepicker();
  	$("#pagamento").datepicker();

  	$("#valor").mask('000.000.000.000.000,00', {reverse: true});

 	var comprovante = $("#comprovante").val();

    if(comprovante) { // returns true if the string is not empty
        alert(comprovante + " existe");
    } else { // no file was selected
        $("#pagamento").prop('disabled',true);
    }

    $( "#comprovante" ).change(function() {
  		$("#pagamento").prop('disabled',false);
  		$("#situacao").val('pago');
	});

	
	  	
 
});


</script>

@stop

resources/views/admin/cadastro-unidade.blade.php
@extends('adminlte::page')



@section('content')

	<div class="box box-primary">
	
	<div class="box-header with-border">
		<h3 class="box-title">Cadastrar unidade</h3>
	</div>

	

	{!! Form::open(['route'=>'unidades.store']) !!}

	@include('admin.partials.form-unidade')
	
	

      			<div class="box-footer">
                <a href="{{route('unidades.index')}}" class="btn btn-default">Voltar</a>
                <button type="submit" class="btn btn-info">Cadastrar</button>
              	</div>
    	
    
	
	{!! Form::close() !!}

@endsection

resources/views/admin/detalhe-empresa.blade.php
@extends('adminlte::page')
@section('content_header')
<h1>Detalhes da empresa</h1>
@stop
@section('content')
@if (session()->has('success'))

<div class="alert alert-success alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
  {{ session('success') }}
</div>
@endif
<div class="row">
  <div class="col-md-12">
    @include('admin.components.widget-detalhes')
    @include('admin.components.widget-unidades')
    
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    
    @include('admin.components.widget-servicos')
    
  </div>
  <div class="col-md-6">
    
    @include('admin.components.widget-taxas')
    
  </div>

  <div class="col-md-6">
        
        @include('admin.components.widget-arquivos')
        
    </div>
</div>

@endsection

@section('js')
<script>

  

    $(function () {
        
        $('#servicos').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": true,
          "ordering": true,
          "info": false,
          "autoWidth": false,
           "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"
            }


        });

        
  });


</script>
@endsection

resources/views/admin/detalhe-unidade.blade.php
@extends('adminlte::page')
@section('content_header')
<h1>Detalhes da unidade</h1>
@stop
@section('content')
@if (session()->has('success'))

<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
    {{ session('success') }}
</div>
@endif
<div class="row">
    <div class="col-md-12">
        
        @include('admin.components.widget-detalhes')
        
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <div class="box box-gray collapsed-box">
          <div class="box-header with-border">
            <a href="#" data-widget="collapse"><h3 class="box-title">Cadastrar novo</h3></a>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
          </div>
          
          <!-- /.box-header -->
          <div class="box-body">
            <a href="{{route('servicos.create', ['id'=>$dados->id,'t'=>substr($route, 0,7),'tipoServico'=>'nRenovaveis'])}}" class="btn btn-block btn-default btn-flat">Projeto/Licença Não Renovável</a>
            <a href="{{route('servicos.create', ['id'=>$dados->id,'t'=>substr($route, 0,7),'tipoServico'=>'controleCertidoes'])}}" class="btn btn-block btn-default btn-flat">Controle de Certidões</a>
            <a href="{{route('servicos.create', ['id'=>$dados->id,'t'=>substr($route, 0,7),'tipoServico'=>'controleTaxas'])}}" class="btn btn-block btn-default btn-flat">Controle de Taxas</a>
            <a href="{{route('servicos.create', ['id'=>$dados->id,'t'=>substr($route, 0,7),'tipoServico'=>'facilitiesRealEstate'])}}" class="btn btn-block btn-default btn-flat">Facilities/Real Estate</a>
            <a href="{{route('servicos.create', ['id'=>$dados->id,'t'=>substr($route, 0,7),'tipoServico'=>'licencaOperacao'])}}" class="btn btn-block btn-default btn-flat">Licença de Operação</a>

          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <div class="col-md-9">
        
            @include('admin.components.widget-arquivos')
        
        
       
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        
        @if(count($servicos->where('tipo','licencaOperacao')))
            @include('admin.components.widget-licencasOperacao')
        @else
        
       
      
        @endif
    
    </div>
    <div class="col-md-6">
        
        @if(count($servicos->where('tipo','nRenovaveis')))
            @include('admin.components.widget-naoRenovaveis')
            @else
           
        
        @endif
       
        
    </div>

    <div class="col-md-6">
        
        @if(count($servicos->where('tipo','controleCertidoes')))
            @include('admin.components.widget-controleCertidoes')
        @else
            
        @endif
       
        
    </div>

    <div class="col-md-6">
        
        @if(count($servicos->where('tipo','controleTaxas')))
            @include('admin.components.widget-controleTaxas')
            @else
           
        @endif
       
        
    </div>
    <div class="col-md-6">
        
        @if(count($servicos->where('tipo','facilitiesRealEstate')))
            @include('admin.components.widget-facilities')
        @else
       
        @endif
       
        
    </div>


    

     
</div>
@endsection

resources/views/admin/editar-pendencia.blade.php
@extends('adminlte::page')



@section('content')

	<div class="box box-primary">
	
	<div class="box-header with-border">
		<h3 class="box-title">Editar pendencia</h3>
	</div>

	

{!! Form::model($pendencia,['route'=>['pendencia.update', $pendencia->id],'method'=>'put','enctype'=>'multipart/form-data']) !!}

	@include('admin.partials.form-pendencia')
	
	

      			<div class="box-footer">
      			<a href="{{route('servicos.show',$pendencia->servico_id)}}" class="btn btn-default">Voltar</a>
                
                <button type="submit" class="btn btn-info">Editar</button>
              	</div>
    	
    
	
	{!! Form::close() !!}

@endsection

@section('js')

<script>
	
	$(document).ready(function() {

  	$("#emissao").datepicker();
  	$("#vencimento").datepicker();
  	 	
  	$("#valor").mask('000.000.000.000.000,00', {reverse: true});
	  	
 
});


</script>

@stop

resources/views/admin/editar-unidade.blade.php
@extends('adminlte::page')

@section('content_header')
<h1>Editar unidade {{$unidade->nomeFantasia}}</h1>
@stop


@section('content')
@if(Session::has('errors'))
@foreach($errors->all() as $error)

<div class="alert alert-danger alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<h4><i class="icon fa fa-ban"></i> Aviso!</h4>
	{!! $error !!}
</div>
@endforeach
@endif

<div class="box box-primary">
	
	
	
	{!! Form::model($unidade,['route'=>['unidade.editar', $unidade->id]]) !!}
	@include('admin.partials.form-unidade')
	<div class="box-footer">
		<a href="{{route('unidades.index')}}" class="btn btn-default">Voltar</a>
		<button type="submit" class="btn btn-info">Editar</button>
	</div>
	
	
	{!! Form::close() !!}
	@endsection

resources/views/admin/lista-pendencias.blade.php
@extends('adminlte::page')

@section('content')


<div class="row">
    <div class="col-lg-12 col-xs-12">
        
        <div class="box box-warning">
            <div class="box-header with-border">
              <h3 class="box-title">{{$title}}</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table id="lista-pendencias" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Cod.</th>
                    <th>Unidade</th>
                    <th>Serviço</th>
                    <th>Pendência</th>
                    <th>Data</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach($pendencias->where('status','pendente') as $p)
                  <tr>
                    <td><a href="{{route('servicos.show',$p->servico_id)}}">{{$p->servico['unidade']['codigo']}}</a></td>
                    <td><a href="{{route('servicos.show',$p->servico_id)}}">{{$p->servico['unidade']['nomeFantasia']}}</a></td>
                    <td><a href="{{route('servicos.show',$p->servico_id)}}">{{$p->servico['nome']}}</a></td>
                    <td><a href="{{route('servicos.show',$p->servico_id)}}">{{$p->pendencia}}</a></td>
                    <td><a href="{{route('servicos.show',$p->servico_id)}}">
                    @switch($p->vencimento)
                        
                        @case($p->vencimento > date('Y-m-d'))
                            <span class="label label-success">{{ \Carbon\Carbon::parse($p->vencimento)->format('d/m/Y')}}</span>
                        @break

                        @case($p->vencimento < date('Y-m-d'))
                            <span class="label label-danger">{{ \Carbon\Carbon::parse($p->vencimento)->format('d/m/Y')}}</span>
                        @break

                        @case($p->vencimento == date('Y-m-d'))
                            <span class="label label-warning">{{ \Carbon\Carbon::parse($p->vencimento)->format('d/m/Y')}}</span>
                        @break





                  @endswitch</a></td>
                  </tr>
                    @endforeach
                  
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              
            </div>
            <!-- /.box-footer -->
          </div>

    </div>

</div>





@endsection

resources/views/admin/lista-unidades.blade.php
@extends('adminlte::page')
@section('content_header')
    <h1>Listagem de unidades</h1>
@stop


@section('content')
			

			<div class="box">
				<div class="box-header">
					<a class="btn btn-app" href="{{route('unidade.cadastro')}}">
	                		<i class="fa fa-plus"></i> Cadastrar
	         			</a>
				<div class="pull-right">
					

					<div class="btn-group-vertical" style="padding-left:20px;">
						<p class="text-left "><b>CB: </b><small>AVCB</small></p>
						<p class="text-left "><b>AS: </b><small>Alvará Sanitário</small></p>


					</div>
					<div class="btn-group-vertical" style="padding-left:20px;">

					<p class="text-left"><b>AF: </b><small>Alvará de Funcionamento</small></p>
					<p class="text-left "><b>AP: </b><small>Alvará de Publicidade</small></p>
					
					
                      
                  </div>
                  <div class="btn-group-vertical" style="padding-left:20px;">
                  	<p class="text-left "><b>PC: </b><small>Alvará da Polícia Civil</small></p>
					<p class="text-left "><b>LA: </b><small>Licença Ambiental</small></p>
					
                     
                    </div>
				</div>

				</div>
	         	


				<div class="box-body">

				

				<table id="lista-unidades" class="table table-bordered table-hover">
                <thead>
                <tr>
                 
                  <th>Cod.</th>
                  <th>Nome Fantasia</th>
                  <th>CNPJ</th>
                  <th>Cidade/UF</th>
                  <th>Licenças</th>
                  
                  
                  <th></th>
                </thead>
                <tbody>
				@foreach($unidades as $unidade)
                	<tr>

	              	<td>{{$unidade->codigo}}</td>
	              	
	              	<td><a href="{{route('unidades.show', $unidade->id)}}">{{$unidade->nomeFantasia}}</a></td>
	              	<td>{{$unidade->cnpj}}</td>
	              	<td>{{$unidade->cidade}}/{{$unidade->uf}}</td>
	              	<td>
	              	@php

	              	$lic = $unidade->servicos->where('tipo','licencaOperacao')->sortByDesc('created_at')->unique('nome');
					
					  

	              	foreach($lic as $l)
	              	{	

	              		if($l->licenca_validade >= date('Y-m-d'))
		              		{
		              			$label = "btn btn-success btn-xs";
		              		}
		              	elseif($l->licenca_validade < date('Y-m-d'))
		              	{

		              		$label = "btn btn-danger btn-xs";
		              	}



	              		
	              		switch($l->nome){
	              			case 'Alvará de Publicidade':
	              			$name = "AP";

	              			break;
	              			
	              			case 'Alvará Sanitário':
	              			$name = "AS";
	              			break;

	              			case 'Alvará da Polícia Civil':
	              			$name = "PC";
	              			break;

	              			case 'AVCB':
	              			$name = "CB";
	              			break;

	              			case 'Alvará de Funcionamento':
	              			$name = "AF";
	              			break;

	              			case 'Licença Ambiental':
	              			$name = "LA";
	              			break;

	              		}

	              		if(empty($name))
	              		{
	              			$name = "n/a";
	              		}

	              		
	              		echo "<a href='/admin/servicos/".$l->id."' type=button class='".$label."'>".$name."</a>";
	              	}

	              	@endphp

	              	</td>
	              	
					<td>
						<div class="btn-group">
                  <button type="button" class="btn btn-default btn-flat">Ações</button>
                  <button type="button" class="btn btn-default btn-flat dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                  </button>
                  <ul class="dropdown-menu" role="menu">

                  	<li><a href="#">Taxas</a></li>
                  	<li class="divider"></li>
                    <li><a href="{{route('unidades.show', $unidade->id)}}">Detalhes</a></li>
                    <li><a href="{{route('unidades.edit', $unidade->id)}}">Editar</a></li>
                    <li><a href="{{route('unidade.delete', $unidade->id)}}" class="confirmation">Excluir</a></li>
                                    
				  </ul>
				  
                </div>
</td>
	                </tr>
	            @endforeach
                </tbody>
			  </table> 
			  
			</div>
		</div>
	 		
@stop

@section('js')
<script src="http://cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"></script>
<script>
		$(function () {
		    $('#lista-unidades').DataTable({
		      "paging": true,
		      "lengthChange": true,
		      "searching": true,
		      "ordering": true,
		      "info": true,
		      "autoWidth": false,
		       "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"
            }
		     
		    });
		    $('.confirmation').on('click', function () {
        		return confirm('Você deseja excluir a unidade?\nTodos os dados relacionados a ela serão excluidos.');
    			});
  });
    </script>
  @stop